### ISSUE TITLE
Not reporting coverage data with Jest 26

### ISSUE THREAD

**Issue by wolesolana** [gabrieli/jest-serial-runner#7]
With `jest-26.0.1`, all test ran using the `jest-serial-runner` do not report any coverage statistics. Instead this is what is reported:
```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```
Any ideas on how to fix this?

**Comment by Keimeno** [comment]
The bug happens because jest-serial-runner uses it's own TestRunner. However there must be some default watch configuration going on that wasn't turned off.

Also, I'm not sure what you need to change in the TestRunner configuration exactly to make this work, but I  know a workaround. You can uninstall jest-serial-runner and use the `--runInBand` option when running jest. As the runInBand option does the exact same thing now as can be seen here [TestScheduler#L203](https://github.com/facebook/jest/blob/master/packages/jest-core/src/TestScheduler.ts#L203). However it will continue to show the coverage.

**Comment by wolesolana** [comment]
Thanks for the suggestion @Keimeno. We fixed this by adding a custom serial runner file that has the same content as the [index.js](https://github.com/gabrieli/jest-serial-runner/blob/master/index.js) file of this project. We then used that in our `jest.config.js` like so: 
```js
runner: '<path-to-custom-runner-file>',
```
I think all that is necessary to fix this in the project is to update the version of `jest` used.

**Comment by evandwight** [comment]
Switching jest-runner to a peer dependency that accepts any version newer than 24 should fix these style of problems permanently.

I submitted a [pull request](https://github.com/gabrieli/jest-serial-runner/pull/14#issue-722019367) but if you want to use this change immediately use [jest-serial-runner2](https://www.npmjs.com/package/jest-serial-runner2).

**Comment by gabrieli** [comment]
@evandwight Thanks for the pr! I've released a new version just now.

**Comment by evandwight** [comment]
Thanks!
